### ISSUE TITLE
Implement In-App Messaging System

### ISSUE THREAD

**Issue by Balance8** [Ionia-Devs/chameleon#1]
### Ticket: Implement In-App Messaging System Using shadcn-chat

**User Story**: As a user, I want an in-app messaging system so that I can communicate directly with photographers or cosplayers after matching.

https://github.com/jakobhoeg/shadcn-chat

#### Description
Integrate a front-end based in-app messaging system using the shadcn-chat component in a Next.js 14 environment. The UI should be enhanced with Radix UI and styled using Tailwind CSS, focusing on front-end functionalities without backend considerations for this phase.

#### Acceptance Criteria
1. **Messaging Feature**: Leverage shadcn-chat for real-time messaging capabilities.
2. **Integration with User Profiles**: Ensure messages link with user profiles for personalized chats.
3. **UI/UX Design**: Design the interface with Radix UI and Tailwind CSS for a responsive, accessible experience.

#### Dependencies
- Pre-existing user matching functionality.
- Front-end setup with Next.js 14, Radix UI, and Tailwind CSS.

#### Time Estimate
- 8 days for front-end development and integration.
- 2 days for testing and refinement.

**Comment by Balance8** [comment]
https://github.com/jakobhoeg/shadcn-chat

**Comment by DinDin985** [comment]
Update from chrome caused a bug with the library "tailwind-scrollbar". This caused the library to stop working and the styling of the scrollbar has malfunctioned. I looked into the github repository and the owner is aware of the problem and create a pseudo fix, but only works for a few of it's features.
![Tailwind-scrollbar-fixJPG](https://github.com/Ionia-Devs/chameleon/assets/100187027/aff2f83e-3e8e-4845-90b5-472e68e0d084)
